apiVersion: db.pedag.io/v1
kind: Table
metadata:
  name: users-table
spec:
  name: Users
  columns:
  - name: Id
    kind: int
  - name: Name
    kind: varchar(50)
  - name: Email
    kind: varchar(255)
  - name: Active
    kind: bit
